### ISSUE TITLE
Update marketing site texts

### ISSUE THREAD

**Issue by liorhorn** [iot-platform/dataflow-product-sync#11]
Fill in placeholders in presentation from Devang

**Comment by liorhorn** [comment]
Sent proposed texts to Devang:

> Slide 11:
> **Global Connectivity & Management**
> Seamlessly purchase, provision and manage SIMs for your devices, leveraging AT&T LTE-M network for low-power cellular network connectivity, and AT&T global SIM connectivity, thereby providing greater reliability, security and mobility.
>
> **Solution Automation**
> Use industry vertical solution templates in orchestration with a rules engine, to identify events and trigger actions and notification. Manage your business and use command & control capabilities to manage your connected business.
>
>
> Slide 12:
> **Device & Device Adapter**
> High flexibility in connecting your devices to the platform: Connect your devices to the AT&T DataFlow platform with a low-footprint client library in a development language of your choice; or use a device adapters on the platform, to connect your devices without changing their code or protocols.
>
> Slide 13:
> **IoT Connectivity and Management**
>IoT devices connect using different access technologies, different network operators, throughout different regions of the world. Visualize all your devices in Multi Network Connect, to manage those diverse endpoints with one comprehensive view of all your IoT devices.

[DataFlow mkt site update.pptx](https://github.com/iot-platform/dataflow-product-sync/files/2067463/DataFlow.mkt.site.update.pptx)

**Comment by jchamma** [comment]
waiting for Devang confirmation on the texts proposed by Lior

**Comment by jchamma** [comment]
@Devang12 please review / confirm until today end of day, otherwise we must continue to avoid delays on the implementation.

**Comment by shaanl** [comment]
@jchamma Good to Go..

From: PATEL, DEVANG 
Sent: Wednesday, June 06, 2018 10:17 AM
To: LAGISETTY, PRASHANTH <pl639j@att.com>; HORN, LIOR <lh866k@intl.att.com>; BENDET, NAOMI <nb886x@intl.att.com>
Cc: CHAMMA, JONATHAN <jv2603@intl.att.com>
Subject: RE: Marketing Site textual updates - Need approval from Devang

Works for me to update the site.

Thanks,
Devang
From: LAGISETTY, PRASHANTH 
Sent: Wednesday, June 06, 2018 9:43 AM
To: HORN, LIOR <lh866k@intl.att.com>; BENDET, NAOMI <nb886x@intl.att.com>; PATEL, DEVANG <DP171K@att.com>
Cc: CHAMMA, JONATHAN <jv2603@intl.att.com>
Subject: Marketing Site textual updates - Need approval from Devang


Hi Devang
Here are the changes: Please review and let the dev team know of your approval/changes:

Slide 11:
Global Connectivity & Management
Seamlessly purchase, provision and manage SIMs for your devices, leveraging AT&T LTE-M network for low-power cellular network connectivity, and AT&T global SIM connectivity, thereby providing greater reliability, security and mobility.
Solution Automation
Use industry vertical solution templates in orchestration with a rules engine to identify events and trigger actions and notifications. Manage your connected business by using command & control capabilities of Dataflow.
Slide 12:
Device & Device Adapter
High flexibility in connecting your devices to the platform: Connect your devices to the AT&T DataFlow platform with a low-footprint client library in a development language of your choice; or use a device adapters on the platform to connect your devices without changing their code or protocols.
Slide 13:
IoT Connectivity and Management
IoT devices connect using different access technologies, different network operators, throughout different regions of the world. Visualize all your devices in Multi Network Connect, to manage those diverse endpoints with one comprehensive view of all your IoT devices.
