### ISSUE TITLE
Device Template Onboarding - Team responsibility

### ISSUE THREAD

**Issue by jchamma** [iot-platform/dataflow-product-sync#6]
Define and corroborate which team will be taking ownership to be in communication with the Device OEM development team to onboard, review, amend and approve/reject new device templates submitted by manufacturers

**Comment by jchamma** [comment]
Discussed during the last grooming call and Product Marketing decided we (Dataflow team) should take care of approval process of new templates. Shayan as the person in charge of the communication and the collaboration with device OEM manufacturers will be the point of contact in case we need help, integration and interaction with the person and team submitting the new templates.

**Comment by sjothunj** [comment]
@jchamma why was this issue closed? Has the process been defined somewhere or did this just mean that Shayan would be on point?
